HW 10
Otus-DevOps-2022-11/nwomib_infra pull request #10
Opened 2023-01-28 13:00 UTC by nwomib

# Выполнено ДЗ № HW 10

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
Протестили создание юзеров (безопасным образом), поигрались с шаблонами.

## Как запустить проект:

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-01-28 14:22 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Нужны небольшие правки, комментарий оставил =)

2023-01-28 14:22 UTC, mrgreyves commented on ansible/environments/prod/playbooks/packer_app.yml
> +  - name: Install git
Вот тут съехало форматирование =)

2023-01-29 13:11 UTC, nwomib commented on ansible/environments/prod/playbooks/packer_app.yml
> +  - name: Install git
Исправил но ошибки всёравно есть(  требуется ли их исправлять? или это косяк проверки?

2023-01-29 15:34 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарии к файлам
Нужно внести совсем небольшие правки =)

2023-01-29 15:34 UTC, mrgreyves commented on ansible/environments/prod/playbooks/packer_app.yml
> +    ansible.builtin.apt:
Обновление кэша пакетного менеджера лучше добавить в шаг установки пакета =)

2023-01-29 15:34 UTC, mrgreyves commented on ansible/playbooks/app.yml
> +    systemd: name=puma state=reloaded
Нужно добавить пустую строку в конец файла =)

2023-01-30 12:28 UTC, nwomib commented
Вроде всё поправил, прошу проверить.

2023-01-31 15:40 UTC, mrgreyves approved these changes
Здравствуйте!)
Как то странновато отработал GA
Все теперь хорошо с дз, апрув ^_^

2023-02-01 05:11 UTC, merged