Play travis
Otus-DevOps-2022-11/nwomib_infra pull request #2
Opened 2022-12-17 11:08 UTC by nwomib

2022-12-18 12:25 UTC, mrgreyves requested changes
Здравствуйте!)
Вам нужно добавить github workflow для тестов и тд
Все эти действия описаны в методичке
ДЗ возвращаю на доработку

2022-12-18 15:30 UTC, nwomib commented
Вроде как все поправил.

2022-12-19 18:25 UTC, nwomib commented
Поправил можно проверять.

2022-12-19 18:54 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь апрув ^_^

2022-12-20 04:38 UTC, merged